# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
services:
  rolle:
    build: .
    command: ["uvicorn", "--factory", "os2mo_rollekatalog.app:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      LOG_LEVEL: "DEBUG"

      # OS2mo
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__AUTH_REALM: "mo"
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      FASTRAMQPI__DATABASE__HOST: "db"
      FASTRAMQPI__DATABASE__USER: "rollekatalog"
      FASTRAMQPI__DATABASE__PASSWORD: "hemmelighed"
      FASTRAMQPI__DATABASE__NAME: "rollekatalog"

      # Rollekatalog
      ROLLEKATALOG_URL: "https://example.rollekatalog.dk"
      API_KEY: "secret"
      INTERVAL: "15"
      ITSYSTEM_USER_KEY: "Active Directory"
      ROOT_ORG_UNIT: "7a8e45f7-4de0-44c8-990f-43c0565ee505"  # Skole og Børn
      SYNC_TITLES: "true"
    networks:
      - default
      - os2mo_default
    volumes:
      - ./:/app/:ro
    ports:
      - 127.0.0.1:8000:8000

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "rollekatalog"
      POSTGRES_PASSWORD: "hemmelighed"
      POSTGRES_DB: "rollekatalog"

networks:
  os2mo_default:
    external: true
