# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
services:
  rolle:
    build: .
    command: ["uvicorn", "--factory", "os2mo_rollekatalog.app:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      LOG_LEVEL: "DEBUG"

      # OS2mo
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__AUTH_REALM: "mo"
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"

      # Rollekatalog
      # TODO
    volumes:
      - ./:/app/:ro

networks:
  default:
    external: true
    name: os2mo_default
