# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
services:
  rolle:
    build: .
    command: ["uvicorn", "--factory", "os2mo_rollekatalog.app:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__LOG_LEVEL: "INFO"
      FASTRAMQPI__JSON_LOGS: "false"

      # OS2mo
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__AUTH_REALM: "mo"
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      FASTRAMQPI__DATABASE__HOST: "db"
      FASTRAMQPI__DATABASE__USER: "rollekatalog"
      FASTRAMQPI__DATABASE__PASSWORD: "hemmelighed"
      FASTRAMQPI__DATABASE__NAME: "rollekatalog"

      # Rollekatalog
      SYNC_ENABLED: "true"
      ROLLEKATALOG_URL: "http://rollekatalog:8090"
      API_KEY: "00000000-0000-4000-0000-000000000000"
      INTERVAL: "15"
      AD_ITSYSTEM_USER_KEY: "OpenDesk"
      FK_ITSYSTEM_USER_KEY: "Office365"
      ROOT_ORG_UNIT: "7a8e45f7-4de0-44c8-990f-43c0565ee505"  # Skole og Børn
      SYNC_TITLES: "true"
    networks:
      - default
      - os2mo_default
    volumes:
      - ./:/app/:ro
    ports:
      - 127.0.0.1:8000:8000

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "rollekatalog"
      POSTGRES_PASSWORD: "hemmelighed"
      POSTGRES_DB: "rollekatalog"

  maria:
    image: mariadb:10.11
    environment:
      MARIADB_USER: 'rollekatalog'
      MARIADB_PASSWORD: 'Test1234'
      MARIADB_DATABASE: 'rollekatalog'
      MARIADB_ROOT_PASSWORD: 'Test1234'

  rollekatalog:
    image: rollekatalog/linux:2025-05-26
    ports:
      - 8090:8090
    environment:
      rc.customer.cvr: "12345678"
      rc.customer.apikey: "00000000-0000-4000-0000-000000000000"
      rc.scheduled.enabled: "true"
      rc.titles.enabled: "true"

      spring.datasource.username: "rollekatalog"
      spring.datasource.password: "Test1234"
      spring.datasource.url: "jdbc:mariadb://maria/rollekatalog"
      spring.datasource.driver-class-name: "org.mariadb.jdbc.Driver"
      spring.flyway.locations: "classpath:db/migration/mysql"

      di.saml.sp.baseUrl: "http://localhost:8090"
      di.saml.sp.entityId: "http://localhost:8090"
      di.saml.idp.metadataLocation: "url:http://idp:8080/simplesaml/saml2/idp/metadata.php"
      # Keystores are a java thing. I created this with the keystore-explorer
      # GUI. Its a keystore with the password "1234" and a RSA Key Pair with
      # the Common Name "localhost".
      di.saml.keystore.location: "file:///home/cert/keystore.pfx"
      di.saml.keystore.password: "1234"

      rc.integrations.kspcics.enabled: "false"
      rc.integrations.kombit.enabled: "false"
      rc.integrations.email.enabled: "false"
    volumes:
      - ./dev-environment/rollekatalog/cert:/home/cert

  idp:
    image: magentaaps/simplesamlphp:master
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:8090
      - SIMPLESAMLPHP_BASEURLPATH=http://localhost:8050/simplesaml
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:8090/saml/login
      - SIMPLESAMLPHP_SECRET_SALT=supersecret
    volumes:
      - ./dev-environment/simplesaml/authsources.php:/var/www/simplesamlphp/config/authsources.php
      - ./dev-environment/simplesaml/saml20-idp-hosted.php:/var/www/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./dev-environment/simplesaml/cert:/var/www/simplesamlphp/cert
    ports:
      - "8050:8080"


networks:
  os2mo_default:
    external: true
