# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
root_organisation:
  municipality_code: null

facets:
  engagement_job_function:
    Jurist:
      title: "Jurist"
      scope: "TEXT"
  org_unit_type:
    Afdeling:
      title: "Afdeling"
      scope: "TEXT"
  engagement_type:
    Ansat:
      title: "Ansat"
      scope: "TEXT"
